# Generated by Django 4.2.28 on 2026-02-13 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_equipment_inventory_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_bookings', to='store.staff', verbose_name='ผู้ประสานงาน'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='coordinator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.staff', verbose_name='ผู้ประสานงาน'),
        ),
    ]
