# Generated by Django 4.2.28 on 2026-02-17 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_historicalbookingassignment_bookingassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbookingassignment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='historicalbookingassignment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='historicalbookingassignment',
            name='history_user',
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.equipment', verbose_name='อุปกรณ์ที่ระบุ (Optional)'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ (สภาพตอนคืน)'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่คืน'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='status',
            field=models.CharField(blank=True, choices=[('picked', 'รับของแล้ว (Picked Up)'), ('returned', 'คืนของแล้ว (Returned)'), ('missing', 'สูญหาย (Missing)'), ('damaged', 'ชำรุด (Damaged)')], default='picked', max_length=20, verbose_name='สถานะคืน'),
        ),
        migrations.AlterField(
            model_name='bookingstaff',
            name='daily_rate_at_booking',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='BookingAssignment',
        ),
        migrations.DeleteModel(
            name='HistoricalBookingAssignment',
        ),
    ]
