# Generated by Django 4.2.28 on 2026-02-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_historicalbookingassignment_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='หมดอายุการจอง (ชำระเงินภายใน)'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='หมดอายุการจอง (ชำระเงินภายใน)'),
        ),
    ]
