# Generated by Django 4.2.28 on 2026-02-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_booking_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='โค้ดส่วนลด')),
                ('discount_percent', models.IntegerField(default=0, help_text='ใส่ 0 หากต้องการใช้ส่วนลดเป็นจำนวนเงิน', verbose_name='ส่วนลด (เปอร์เซ็นต์ %)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='ใส่ 0 หากต้องการใช้ส่วนลดเป็น %', max_digits=10, verbose_name='ส่วนลด (จำนวนบาท)')),
                ('valid_from', models.DateTimeField(verbose_name='เริ่มใช้ได้ตั้งแต่')),
                ('valid_to', models.DateTimeField(verbose_name='หมดอายุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
            ],
            options={
                'verbose_name_plural': 'ตั้งค่า - โค้ดส่วนลด (Promotions)',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดส่วนลดรวม'),
        ),
        migrations.AddField(
            model_name='booking',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าปรับ (ส่งคืนช้า, ของชำรุด ฯลฯ)'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดส่วนลดรวม'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าปรับ (ส่งคืนช้า, ของชำรุด ฯลฯ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='late_fee_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ค่าปรับส่งคืนช้า (ต่อวัน)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='สิทธิพาร์ทเนอร์ (Partner)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_discount_percent',
            field=models.IntegerField(default=10, verbose_name='เปอร์เซ็นต์ส่วนลดพาร์ทเนอร์'),
        ),
        migrations.AddField(
            model_name='booking',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.promotioncode', verbose_name='โค้ดส่วนลดที่ใช้'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='promotion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.promotioncode', verbose_name='โค้ดส่วนลดที่ใช้'),
        ),
    ]
