# Generated by Django 4.2.27 on 2026-02-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_promotioncode_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='บันทึกภายใน (Staff Only)'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='บันทึกภายใน (Staff Only)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'รอตรวจสอบ (Draft)'), ('pending', 'รออนุมัติ (Pending)'), ('approved', 'อนุมัติแล้ว (Approved)'), ('active', 'กำลังใช้งาน (Active)'), ('overdue', 'เกินกำหนด (Overdue)'), ('completed', 'คืนของครบ (Completed)'), ('cancelled', 'ยกเลิก (Cancelled)')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='status',
            field=models.CharField(choices=[('draft', 'รอตรวจสอบ (Draft)'), ('pending', 'รออนุมัติ (Pending)'), ('approved', 'อนุมัติแล้ว (Approved)'), ('active', 'กำลังใช้งาน (Active)'), ('overdue', 'เกินกำหนด (Overdue)'), ('completed', 'คืนของครบ (Completed)'), ('cancelled', 'ยกเลิก (Cancelled)')], default='draft', max_length=20),
        ),
    ]
