# Generated by Django 4.2.27 on 2026-03-04 03:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_booking_internal_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่บริการ')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ตั้งค่า - หมวดหมู่บริการ',
            },
        ),
        migrations.RemoveField(
            model_name='bookingstaff',
            name='daily_rate_at_booking',
        ),
        migrations.AddField(
            model_name='bookingstaff',
            name='assigned_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 3, 4, 3, 32, 55, 336709, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingstaff',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff', to='store.booking'),
        ),
        migrations.AlterField(
            model_name='bookingstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.staff'),
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อบริการ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเริ่มต้น (ต่อวัน/โปรเจกต์)')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้บริการ')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.servicecategory', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'บริการ (Service)',
                'verbose_name_plural': 'ทรัพยากร - บริการ',
            },
        ),
        migrations.CreateModel(
            name='HistoricalServiceOffer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อบริการ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเริ่มต้น (ต่อวัน/โปรเจกต์)')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้บริการ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.servicecategory', verbose_name='หมวดหมู่')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical บริการ (Service)',
                'verbose_name_plural': 'historical ทรัพยากร - บริการ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BookingServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_services', to='store.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.serviceoffer')),
            ],
        ),
    ]
