# Generated by Django 4.2.27 on 2026-03-04 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_servicecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_bookings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ประสานงาน (Staff)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='assigned_as_staff', through='store.BookingStaff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='พนักงาน'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='coordinator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ประสานงาน (Staff)'),
        ),
        migrations.DeleteModel(
            name='HistoricalStaff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffPosition',
        ),
    ]
