# Generated by Django 4.2.27 on 2026-03-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_staff_created_by_remove_staff_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplashConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='เปิดใช้งาน Splash Screen')),
                ('title', models.CharField(default='น้อมสำนึกในพระมหากรุณาธิคุณอันหาที่สุดมิได้', max_length=200, verbose_name='หัวข้อข้อความ')),
                ('message', models.TextField(default='ข้าพระพุทธเจ้า คณะกรรมการ ผู้บริหาร พนักงานและลูกจ้าง\nบริษัท อสมท จำกัด (มหาชน)', verbose_name='เนื้อหาข้อความ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='splash/', verbose_name='รูปภาพพระบรมฉายาลักษณ์ / รูปภาพพื้นหลัง')),
            ],
            options={
                'verbose_name_plural': 'ตั้งค่า - Splash Screen',
            },
        ),
    ]
