# Generated by Django 4.2.27 on 2026-03-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_splashconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'ยังไม่จ่าย (Unpaid)'), ('pending', 'รอตรวจสอบ (Pending Verification)'), ('paid', 'จ่ายแล้ว (Paid)'), ('waived', 'ไม่เก็บมัดจำ (Waived)'), ('refunded', 'คืนเงิน (Refunded)')], default='unpaid', max_length=20, verbose_name='สถานะการชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'ยังไม่จ่าย (Unpaid)'), ('pending', 'รอตรวจสอบ (Pending Verification)'), ('paid', 'จ่ายแล้ว (Paid)'), ('waived', 'ไม่เก็บมัดจำ (Waived)'), ('refunded', 'คืนเงิน (Refunded)')], default='unpaid', max_length=20, verbose_name='สถานะการชำระเงิน'),
        ),
    ]
