# Generated by Django 4.2.27 on 2026-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_add_payment_status_waived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalissuereport',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical issue report', 'verbose_name_plural': 'historical รายงานปัญหา (Issue Reports)'},
        ),
        migrations.AlterModelOptions(
            name='issuereport',
            options={'verbose_name_plural': 'รายงานปัญหา (Issue Reports)'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'การแจ้งเตือน (Notifications)'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'โปรไฟล์ผู้ใช้ (Profiles)'},
        ),
        migrations.AddField(
            model_name='historicalstudio',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='รูปภาพสตูดิโอ'),
        ),
        migrations.AddField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studios/', verbose_name='รูปภาพสตูดิโอ'),
        ),
    ]
