# Generated by Django 4.2.27 on 2026-03-18 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_add_image_to_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='splashconfig',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='กำหนดอัตรามัดจำที่ใช้คำนวณยอดมัดจำของใบจอง เช่น 30 = 30%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='เปอร์เซ็นต์มัดจำ (%)'),
        ),
    ]
