# Generated by Django 4.2.27 on 2026-03-18 09:43

import django.core.validators
from django.db import migrations, models


def seed_booking_config(apps, schema_editor):
    BookingConfig = apps.get_model('store', 'BookingConfig')
    SplashConfig = apps.get_model('store', 'SplashConfig')

    if BookingConfig.objects.exists():
        return

    splash = SplashConfig.objects.order_by('id').first()
    deposit_percent = getattr(splash, 'deposit_percent', 30) if splash else 30
    BookingConfig.objects.create(deposit_percent=deposit_percent)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_splashconfig_deposit_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=30.0, help_text='กำหนดอัตรามัดจำที่ใช้คำนวณยอดมัดจำของใบจอง เช่น 30 = 30%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='เปอร์เซ็นต์มัดจำ (%)')),
            ],
            options={
                'verbose_name_plural': 'ตั้งค่า - ระบบจอง',
            },
        ),
        migrations.RunPython(seed_booking_config, migrations.RunPython.noop),
    ]
