# Generated by Django 4.2.27 on 2026-03-18 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_bookingconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingConfig',
        ),
        migrations.RemoveField(
            model_name='splashconfig',
            name='deposit_percent',
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='เจ้าหน้าที่สามารถปรับ % มัดจำต่อใบจองได้', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='เปอร์เซ็นต์มัดจำ (%)'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='เจ้าหน้าที่สามารถปรับ % มัดจำต่อใบจองได้', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='เปอร์เซ็นต์มัดจำ (%)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดมัดจำ'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดมัดจำ'),
        ),
    ]
