# Generated by Django 4.2.27 on 2026-03-18 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_delete_bookingconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=30.0, help_text='ค่า % มัดจำแบบ global ของระบบ', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='เปอร์เซ็นต์มัดจำ (%)')),
            ],
            options={
                'verbose_name_plural': 'ตั้งค่า - ระบบจอง',
            },
        ),
    ]
