# Generated by Django 4.2.27 on 2026-02-04 09:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='เริ่มใช้')),
                ('end_time', models.DateTimeField(verbose_name='สิ้นสุด')),
                ('status', models.CharField(choices=[('draft', 'รอตรวจสอบ (Draft)'), ('pending', 'รออนุมัติ (Pending)'), ('approved', 'อนุมัติแล้ว (Approved)'), ('active', 'กำลังใช้งาน (Active)'), ('completed', 'คืนของครบ (Completed)'), ('cancelled', 'ยกเลิก (Cancelled)')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'รายการจอง (Booking)',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial Number')),
                ('asset_tag', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='รหัสทรัพย์สิน (QR/Barcode)')),
                ('status', models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('maintenance', 'ส่งซ่อม'), ('lost', 'สูญหาย')], default='available', max_length=20, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name_plural': 'ทรัพยากร - อุปกรณ์รายชิ้น (Asset)',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อแพ็คเกจ')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='คำอธิบายสั้น')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเหมาจ่าย')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='รูปภาพแพ็คเกจ')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='แนะนำ (Highlight)')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name_plural': 'ทรัพยากร - แพ็คเกจ',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
            ],
            options={
                'verbose_name_plural': 'ตั้งค่า - หมวดหมู่สินค้า',
            },
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อตำแหน่ง')),
                ('base_daily_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ค่าแรงเริ่มต้น (Standard Rate)')),
            ],
            options={
                'verbose_name_plural': 'ตั้งค่า - ตำแหน่งพนักงาน',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสตูดิโอ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเช่าต่อวัน')),
                ('turnaround_time', models.DurationField(default=datetime.timedelta(seconds=7200), verbose_name='เวลาทำความสะอาด (Buffer Time)')),
            ],
            options={
                'verbose_name_plural': 'ทรัพยากร - สตูดิโอ',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อพนักงาน')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ค่าแรงต่อวัน (Specific Rate)')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='เพิ่มโดย')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.staffposition', verbose_name='ตำแหน่ง')),
            ],
            options={
                'verbose_name_plural': 'ทรัพยากร - พนักงาน',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเช่าต่อวัน')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวนทั้งหมด')),
                ('turnaround_time', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='เวลาที่ต้องเว้นว่างหลังคืนของ เพื่อเช็ค/ทำความสะอาด', verbose_name='เวลาในการเตรียมของ (Buffer Time)')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้เช่า')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productcategory', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name_plural': 'ทรัพยากร - สินค้า (Product)',
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='items',
            field=models.ManyToManyField(through='store.PackageItem', to='store.product', verbose_name='สินค้าในแพ็คเกจ'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อปัญหา')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('fixed', 'Fixed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.equipment')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.studio')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStudio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสตูดิโอ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเช่าต่อวัน')),
                ('turnaround_time', models.DurationField(default=datetime.timedelta(seconds=7200), verbose_name='เวลาทำความสะอาด (Buffer Time)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical studio',
                'verbose_name_plural': 'historical ทรัพยากร - สตูดิโอ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStaff',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อพนักงาน')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ค่าแรงต่อวัน (Specific Rate)')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='เพิ่มโดย')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.staffposition', verbose_name='ตำแหน่ง')),
            ],
            options={
                'verbose_name': 'historical staff',
                'verbose_name_plural': 'historical ทรัพยากร - พนักงาน',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIssueReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อปัญหา')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('fixed', 'Fixed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.equipment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.studio')),
            ],
            options={
                'verbose_name': 'historical issue report',
                'verbose_name_plural': 'historical issue reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, verbose_name='Serial Number')),
                ('asset_tag', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='รหัสทรัพย์สิน (QR/Barcode)')),
                ('status', models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('maintenance', 'ส่งซ่อม'), ('lost', 'สูญหาย')], default='available', max_length=20, verbose_name='สถานะ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.product', verbose_name='สินค้าหลัก')),
            ],
            options={
                'verbose_name': 'historical equipment',
                'verbose_name_plural': 'historical ทรัพยากร - อุปกรณ์รายชิ้น (Asset)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='เริ่มใช้')),
                ('end_time', models.DateTimeField(verbose_name='สิ้นสุด')),
                ('status', models.CharField(choices=[('draft', 'รอตรวจสอบ (Draft)'), ('pending', 'รออนุมัติ (Pending)'), ('approved', 'อนุมัติแล้ว (Approved)'), ('active', 'กำลังใช้งาน (Active)'), ('completed', 'คืนของครบ (Completed)'), ('cancelled', 'ยกเลิก (Cancelled)')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical booking',
                'verbose_name_plural': 'historical รายการจอง (Booking)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='equipment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.product', verbose_name='สินค้าหลัก'),
        ),
        migrations.CreateModel(
            name='BookingStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='ราคาต่อวัน ณ วันจอง', max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_studios', to='store.booking')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.studio')),
            ],
        ),
        migrations.CreateModel(
            name='BookingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate_at_booking', models.DecimalField(decimal_places=2, help_text='ค่าแรงต่อวัน ณ วันจอง', max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_staff', to='store.booking')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.staff')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_packages', to='store.booking')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.package')),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='ราคาต่อชิ้น ณ วันจอง', max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='packages',
            field=models.ManyToManyField(blank=True, through='store.BookingPackage', to='store.package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(blank=True, through='store.BookingItem', to='store.product'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.ManyToManyField(blank=True, through='store.BookingStaff', to='store.staff'),
        ),
        migrations.AddField(
            model_name='booking',
            name='studios',
            field=models.ManyToManyField(blank=True, through='store.BookingStudio', to='store.studio'),
        ),
        migrations.CreateModel(
            name='ProductionVehicle',
            fields=[
            ],
            options={
                'verbose_name': 'ยานพาหนะ (Vehicle)',
                'verbose_name_plural': 'จัดการยานพาหนะ (Vehicles)',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
    ]
