# Generated by Django 4.2.28 on 2026-02-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์ติดต่อ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อโปรเจค/งาน'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์ติดต่อ'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อโปรเจค/งาน'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='ชื่อลูกค้า'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='ชื่อลูกค้า'),
        ),
    ]
