# Generated by Django 4.2.28 on 2026-02-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_created_at_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='เลขครุภัณฑ์'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='inventory_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='เลขครุภัณฑ์'),
        ),
    ]
