# Generated by Django 4.2.28 on 2026-02-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดมัดจำ (30%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/', verbose_name='สลิปโอนเงิน'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'ยังไม่จ่าย (Unpaid)'), ('pending', 'รอตรวจสอบ (Pending Verification)'), ('paid', 'จ่ายแล้ว (Paid)'), ('refunded', 'คืนเงิน (Refunded)')], default='unpaid', max_length=20, verbose_name='สถานะการชำระเงิน'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดรวมทั้งหมด'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดมัดจำ (30%)'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='payment_slip',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='สลิปโอนเงิน'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'ยังไม่จ่าย (Unpaid)'), ('pending', 'รอตรวจสอบ (Pending Verification)'), ('paid', 'จ่ายแล้ว (Paid)'), ('refunded', 'คืนเงิน (Refunded)')], default='unpaid', max_length=20, verbose_name='สถานะการชำระเงิน'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดรวมทั้งหมด'),
        ),
    ]
