# Generated by Django 4.2.28 on 2026-02-17 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_booking_deposit_amount_booking_payment_slip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBookingAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(blank=True, editable=False, verbose_name='เวลาที่จ่ายของ')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่คืนของ')),
                ('status', models.CharField(choices=[('picked', 'รับของแล้ว (Picked Up)'), ('returned', 'คืนของแล้ว (Returned)'), ('missing', 'สูญหาย (Missing)'), ('damaged', 'ชำรุด (Damaged)')], default='picked', max_length=20, verbose_name='สถานะ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ (สภาพตอนคืน)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('booking', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.booking', verbose_name='รายการจอง')),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.equipment', verbose_name='อุปกรณ์ (ระบุชิ้น)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical booking assignment',
                'verbose_name_plural': 'historical การจ่ายอุปกรณ์ (Assignments)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BookingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่จ่ายของ')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่คืนของ')),
                ('status', models.CharField(choices=[('picked', 'รับของแล้ว (Picked Up)'), ('returned', 'คืนของแล้ว (Returned)'), ('missing', 'สูญหาย (Missing)'), ('damaged', 'ชำรุด (Damaged)')], default='picked', max_length=20, verbose_name='สถานะ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ (สภาพตอนคืน)')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='store.booking', verbose_name='รายการจอง')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='store.equipment', verbose_name='อุปกรณ์ (ระบุชิ้น)')),
            ],
            options={
                'verbose_name_plural': 'การจ่ายอุปกรณ์ (Assignments)',
            },
        ),
    ]
