# Generated by Django 4.2.28 on 2026-02-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_booking_expires_at_historicalbooking_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลลูกค้า (Contact Email)'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลลูกค้า (Contact Email)'),
        ),
    ]
