"""
Django settings for MCOT_Rental_Platform project.
# Trigger Reload 5
Generated by 'django-admin startproject' using Django 5.x.
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-new-project-secret-key-change-in-prod'

DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.serveo.net',
    'https://*.serveousercontent.com'
]

# Application definition

INSTALLED_APPS = [
    # --- Admin Theme (Unfold) ---
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    "unfold.contrib.simple_history",
    
    # --- Django Core ---
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # --- Third Party ---
    'import_export',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_summernote',
    
    # --- Local Apps ---
    'apps.store',  # Main Rental App
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
LANGUAGE_CODE = 'th'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirects
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Summernote
SUMMERNOTE_THEME = 'bs5'

# ==============================================================================
# DJANGO UNFOLD CONFIGURATION
# ==============================================================================
UNFOLD = {
    "SITE_TITLE": "MCOT Rental Platform",
    "SITE_HEADER": "MCOT Rental Admin",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "config.dashboard.dashboard_callback",
    "THEME": "dark",  # Force dark mode or let it follow system
    "STYLES": [
        lambda request: static("css/unfold_custom.css"),
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Operations",
                "separator": True,
                "items": [
                    {
                        "title": "Bookings",
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:store_booking_changelist"),
                    },
                    {
                        "title": "Issue Reports",
                        "icon": "warning",
                        "link": reverse_lazy("admin:store_issuereport_changelist"),
                    },
                ],
            },
            {
                "title": "Inventory",
                "separator": True,
                "items": [
                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:store_product_changelist"),
                    },
                    {
                        "title": "Equipment",
                        "icon": "build",
                        "link": reverse_lazy("admin:store_equipment_changelist"),
                    },
                    {
                        "title": "Studios",
                        "icon": "mic",
                        "link": reverse_lazy("admin:store_studio_changelist"),
                    },
                    {
                        "title": "Packages",
                        "icon": "work_outline",
                        "link": reverse_lazy("admin:store_package_changelist"),
                    },
                    {
                        "title": "Vehicles",
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:store_productionvehicle_changelist"),
                    },
                ],
            },
            {
                "title": "People & Access",
                "separator": True,
                "items": [
                    {
                        "title": "Staff",
                        "icon": "badge",
                        "link": reverse_lazy("admin:store_staff_changelist"),
                    },
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groups",
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
             {
                "title": "Settings",
                "separator": True,
                "items": [
                    {
                        "title": "Product Categories",
                        "icon": "category",
                        "link": reverse_lazy("admin:store_productcategory_changelist"),
                    },
                    {
                        "title": "Staff Positions",
                        "icon": "assignment_ind",
                        "link": reverse_lazy("admin:store_staffposition_changelist"),
                    },
                ],
            },
        ],
    },
}

# Hide Recent Actions if desired
SIMPLEUI_HOME_ACTION = True

# --- Summernote ---
X_FRAME_OPTIONS = 'SAMEORIGIN'
SUMMERNOTE_THEME = 'bs4'
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'summernote': {
        'width': '100%',
        'height': '480',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'clear']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
    },
}
